### ISSUE TITLE
ESSI: SOW

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/essi#10]
# Story

**Implement IiifPrint Gem for Parent/Child Metadata Display (ESSI-1464):**

SoftServ will create a parent/child hierarchy view in Universal Viewer that offers a viewable multi-item complex object with high-level descriptive metadata. It will respond to the following acceptance criteria:

- [x] #14
- [x] #15
- [x] #16
  - [x] https://github.com/scientist-softserv/essi/issues/20
- [x] #17
- [x] #18
- [x] #19 
  - [x] https://github.com/scientist-softserv/iiif_print/issues/152 
- [x] parent/child hierarchy
  - [x] #11 
  - [ ] ~~#13~~ ->  (this has been moved to phase 2)
- [x] auto uv search https://github.com/scientist-softserv/iiif_print/issues/183

- [ ] We will accomplish displaying child works of a parent, their metadata and the collection metadata in a single UV viewer through the use of the IIIF Collection resource type. We will attempt to complete the remaining tasks through the use of the IIIF Range resource type and/or UV configuration options.

- [ ]  Modeled on successful work with University of Louisville, SoftServ will use parent/child hierarchy to achieve the goal specific to collection and item. The Newspaper Gem utilizes a model where Newspaper is the parent, and Page is the child.  The gem can be utilized for other works that follow the same model, and will meet the requirements for medieval manuscripts and other works. It will allow: #13 
  - [ ] All pages when viewing the work (e.g., newspaper, manuscript) to load in the UV
  - [ ] Search across all pages contained in the work

- [ ] ~~If it doesn’t pose any significant technical challenges, SoftServ will target IIIF Presentation 3.  An upgrade to UV 4 is not essential or recommended as part of this work.~~

ref: https://docs.google.com/document/d/1JeHrZGkFtGYPbekWkakVqaBW7ZHhBcZlNAVxDtjH190/edit

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by jillpe** [comment]
Related to [iiif #155](https://github.com/scientist-softserv/iiif_print/issues/155)
