### ISSUE TITLE
Spike: Parent-level metadata can also be viewed in viewer, similar to individual work

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#17]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket

## TESTING INSTRUCTIONS

- [ ]  From the parent UV's "more information" pane, you can expand it and see metadat.
- [ ]  To clarify, Click on a child work. the parent metadata should be displayed at the top of the more info pane for each child work.
- [ ]  The child metadata will be below a section divider called "PAGE". When you scroll down to that section and click through the other child works, it will stay scrolled down to that view.

**Comment by ShanaLMoore** [comment]
On Friday we discussed with Rob that we could just show the parent's title in the pane, then it'll show the dynamic/changing metadata under a section called "PAGE". The user would scroll down (below the UV) to see the rest of its metadata. 

**CON:** 
- a manifest should contain all the metadata: if a university were to share the manifest with someone else, the above implementation would strip out the ability to share parent metadata

**Comment by ShanaLMoore** [comment]
Kirk to demo our current implementation. If they are OK with it, we can close this work. We will keep it open until we can have this discussion.

**Comment by jillpe** [comment]
Per meeting to discuss hierarchy display with Michelle and Julie 2023-04-11 at 12pm Pacific, it was confirmed client is okay with parent metadata displaying in viewer and on all child works in viewer

**Comment by ShanaLMoore** [comment]
## TESTING INSTRUCTIONS

- [ ] From the parent UV's "more information" pane, you can expand it and see metadat. 
- [ ] To clarify, Click on a child work. the parent metadata should be displayed at the top of the more info pane for each child work.
- [ ] The child metadata will be below a section divider called "PAGE". When you scroll down to that section and click through the other child works, it will stay scrolled down to that view.

**Comment by jlhardes** [comment]
This is working when testing the metadata on the following parent/child work: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/cn69m4128?locale=en
