### ISSUE TITLE
Spike: Search in the viewer searches all collection content, not just the current loaded page or child/member item (if possible)

### ISSUE THREAD

**Issue by jillpe** [notch8/essi#19]
# Summary
This was part of the SOW. We want to check if this is working.

# Accepted Criteria
- [ ] If this is working, close ticket. If this is not working, create follow up tickets and close this ticket

# Testing Instructions

- [ ] create a parent/child work
- [ ] search for a metadata term that is in the metadata pane
- [ ] observe that the search returned the result which should be the work that the metadata is on
- [ ]  observe that the parent metadata shows when viewed
- [ ] observe that the child metadata shows when viewed

# Notes

We asked the client to clarify what is meant by the word "collection". ref: https://assaydepot.slack.com/archives/C04CRCV3QNT/p1681148674100579?thread_ts=1681144597.020559&cid=C04CRCV3QNT

![Image](https://user-images.githubusercontent.com/10081604/230971365-873d8c00-293c-4088-8f0f-5d5529328a50.png)

**Comment by ShanaLMoore** [comment]
metadata and ocr search should be supported by iiif_print but it looks like we've got some rework to fix.

**Comment by jlhardes** [comment]
This is working as described. Searching for metadata terms for the parent work or for any of the child works is finding correct matches for each work for the following parent/child work: https://dcadmin-test.dlib.indiana.edu/concern/paged_resources/cn69m4128?locale=en If the parent work or child work has multiple pages, the match is "found" on the first page of the parent work or child work, even though the match is actually for the work's metadata and not particular content within a page.
